packagecom.saurabh.algo.sorting;
publicclassAnagram{

publicstaticintsize;
publicstaticchar[]arrChar=newchar[100];
publicstaticvoidmain(String[]args){
//System.out.println("ddddddd");
Stringcat="cat";
size=cat.length();
for(inti=0;i<size;i++){
arrChar[i]=cat.charAt(i);
}
doAnagram(size);
//displayAnagram();
}
publicstaticvoiddoAnagram(intnewSize){
if(newSize==1)
return;
for(inti=0;i<newSize;i++){
doAnagram(newSize-1);
if(newSize==2)
displayAnagram();
rotateAnagram(newSize);
}
}
privatestaticvoiddisplayAnagram(){
System.out.println("");
for(inti=0;i<size;i++){
System.out.print(""+arrChar[i]+"");
}
System.out.println("");
}
privatestaticvoidrotateAnagram(intnewSize){
intj;
intpos=size-newSize;
chartemp=arrChar[pos];
for(j=pos+1;j<size;j++){
arrChar[j-1]=arrChar[j];
//arrChar[j-1]=temp;
}
arrChar[j-1]=temp;
}


}
